/********************************************************************
* code/RootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error code/RootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRootDict();
extern void G__cpp_setup_inheritanceRootDict();
extern void G__cpp_setup_typetableRootDict();
extern void G__cpp_setup_memvarRootDict();
extern void G__cpp_setup_globalRootDict();
extern void G__cpp_setup_memfuncRootDict();
extern void G__cpp_setup_funcRootDict();
extern void G__set_cpp_environmentRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "code/Waveform.h"
#include "code/LecroyHdfFile.h"
#include "code/LecroyFile.h"
#include "code/V1730File.h"
#include "code/WaveformProcessor.h"
#include "code/DataFile.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RootDictLN_TObject;
extern G__linked_taginfo G__RootDictLN_TNamed;
extern G__linked_taginfo G__RootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootDictLN_TArray;
extern G__linked_taginfo G__RootDictLN_TArrayD;
extern G__linked_taginfo G__RootDictLN_TAttLine;
extern G__linked_taginfo G__RootDictLN_TAttFill;
extern G__linked_taginfo G__RootDictLN_TAttMarker;
extern G__linked_taginfo G__RootDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__RootDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__RootDictLN_TF1;
extern G__linked_taginfo G__RootDictLN_TH1D;
extern G__linked_taginfo G__RootDictLN_TH1;
extern G__linked_taginfo G__RootDictLN_TH1F;
extern G__linked_taginfo G__RootDictLN_TIter;
extern G__linked_taginfo G__RootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__RootDictLN_TProfile;
extern G__linked_taginfo G__RootDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__RootDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__RootDictLN_TH2D;
extern G__linked_taginfo G__RootDictLN_Waveform;
extern G__linked_taginfo G__RootDictLN_DataFile;
extern G__linked_taginfo G__RootDictLN_H5File;
extern G__linked_taginfo G__RootDictLN_DataSet;
extern G__linked_taginfo G__RootDictLN_DataSpace;
extern G__linked_taginfo G__RootDictLN_hsize_t;
extern G__linked_taginfo G__RootDictLN_LecroyHdfFile;
extern G__linked_taginfo G__RootDictLN_TFile;
extern G__linked_taginfo G__RootDictLN_LecroyFile;
extern G__linked_taginfo G__RootDictLN_TMidasFile;
extern G__linked_taginfo G__RootDictLN_TMidasEvent;
extern G__linked_taginfo G__RootDictLN_TDataContainer;
extern G__linked_taginfo G__RootDictLN_V1730File;
extern G__linked_taginfo G__RootDictLN_TGraph;
extern G__linked_taginfo G__RootDictLN_Pulse;
extern G__linked_taginfo G__RootDictLN_WaveformProcessor;

/* STUB derived class for protected member access */
